os: linux
dist: focal
language: node_js
node_js:
    - 14
before_install:
    - pip install --user codecov
    - npm i @cloudflare/wrangler -g
after_success:
    - codecov --file coverage/lcov.info --disable search
