os: linux
dist: bionic
language: node_js
node_js:
    - node
before_install:
    - pip install --user codecov
    - npm i @cloudflare/wrangler -g
after_success:
    - codecov --file coverage/lcov.info --disable search
