os: linux
dist: focal
language: node_js
node_js:
    - node
before_install:
    - pip install --user codecov
    - npm i @cloudflare/wrangler -g
script: ./scripts/run-tests.sh
after_success:
    - codecov --file coverage/lcov.info --disable search
